# Generated by Django 4.2.2 on 2023-06-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0016_alter_librarian_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='id',
        ),
        migrations.AddField(
            model_name='librarian',
            name='librarian_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
